[package]
name = "aptos_pay"
version = "1.0.0"
authors = []

[addresses]
aptos_pay_addr= "0xa5ff95beaa899810ea1909921c33369bd6c20d2ab27812bc925784fb51146d48"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]
